server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # --- 1. SPA-Routing für den Hauptpfad ---
    location / {
        try_files $uri $uri/ /index.html;
    }


    # --- 3. Backend Proxy-Weiterleitung ---
    location /api/ {
        proxy_pass http://it-dashboard-backend:8000;
        
        # Standard-Proxy-Header (empfohlen)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}