server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Alle Anfragen unter /work/ werden richtig ausgeliefert
    location /work/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Optional: andere Pfade auf /index.html umleiten (SPA)
    location / {
        try_files $uri /index.html;
    }
    location /api/ {
    proxy_pass http://it-dashboard-backend:8000/;
    }
}