server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Assets unter /work/ korrekt liefern
    location /work/ {
        try_files $uri $uri/ =404;
    }

    # SPA Routing
    location / {
        try_files $uri /index.html;
    }
}